spring:
  # H2 Database ??
  datasource:
    driver-class-name: org.h2.Driver
    #url: 'jdbc:h2:mem:test'   # H2 DB ?? ?? (In-Memory Mode)
    url: 'jdbc:h2:~/test'    # H2 DB ?? ?? (Embedded Mode)
    username: user        # H2 DB ?? ID (??? ??)
    password: 12345678        # H2 DB ?? PW (??? ??)

  # H2 Console ??
  h2:
    console: # H2 DB? ??? ??? ? ?? ??
      enabled: true           # H2 Console ?? ??
      path: /h2-console       # H2 Console ?? ??

  # JPA ??
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update        # DB ??? ?? (none, create, create-drop, update, validate)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true      # ?? ?? ?? (??)
        show_sql: true        # ?? ?? ??

  ai:
    openai:
      # api-key : ChatGPT API Key
      api-key: ${OPENAI}
      chat:
        options:
          # model : gpt-4o (gpt-4, gpt3.5, gpt-4o...)
          model: gpt-4o
          temperature: 0.7